### ISSUE TITLE
[BUG]: Tagcomplete not working with latest SD:Next

### ISSUE THREAD

**Issue by Woisek** [DominikDoom/a1111-sd-webui-tagcomplete#226]
It seems like the latest SD:Next update broke the tag complete for wildcards. The contents of a wildcard is not displayed anymore.
Could someone check this, please? 🙏

**Comment by DominikDoom** [comment]
Can't reproduce, everything works fine for me on the latest SD.Next commit (48c0ce9b).
So either it got fixed in the meantime or something else is at play, in which case I would need more info. Mainly if there are related errors in the browser console.

**Comment by Woisek** [comment]
Alright, will check again later this day, thanks. 👍

**Comment by Woisek** [comment]
Update:
I updated everything but the problem still exists.
![Zwischenablagebild](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/122026301/ce6d658b-1cd7-465c-93da-ab3641324aee)

After entering the wildcard, the content of it doesn't come up to choose from. Also, if the wildcard menu is open, I can scroll up and down, but pressing enter does not change it. In the screenshot, it stays at __women_bodytype__ not matter what I would select and enter afterwards. 😕

**Comment by DominikDoom** [comment]
Are you sure there are no errors? This pretty much sounds like the file request to read the contents on demand fails. Keep the console open during typing if you haven't tried that yet. Or use the network tab in the browser dev tools to see if failed requests pop up when selecting the entry.

Have you changed the location of your wildcards, extensions or user data path recently? There might be a permissions issue if it is outside of the webui root since I haven't gotten around to adding a proper API endpoint for it. In that case, you would need to add the path to the `--gradio-allowed-path` argument for now (at least that's how it works in the original webui).

**Comment by Woisek** [comment]
I changed nothing, everything is as it was since ever.
The console shows nothing, but between the errors that comes up in the dev tools, I found this:

17:06:17.546
XHRGET
http://localhost:7860/file=extensions/sd-dynamic-prompts/wildcards//clothing_light_women.txt?1693238777545
[HTTP/1.1 403 Forbidden 11ms]

17:06:17.549
XHRGET
http://localhost:7860/file=extensions/sd-dynamic-prompts/wildcards//clothing_light_women.txt?1693238777547
[HTTP/1.1 403 Forbidden 12ms]

17:06:17.558
Error loading file "extensions/sd-dynamic-prompts/wildcards//clothing_light_women.txt?1693238777545": 403 Forbidden [_utils.js:48:17](http://localhost:7860/file=I:/Super%20SD%202.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/_utils.js?1693209103.1752656)
17:06:17.559
Uncaught (in promise) TypeError: null has no properties
    parse http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/ext_wildcards.js?1693209103.176263:38
    processQueueReturn http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/_utils.js?1693209103.1752656:214
    processParsers http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/_utils.js?1693209103.1752656:231
    autocomplete http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/tagAutocomplete.js?1693209103.176263:991
    addAutocompleteToArea http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/tagAutocomplete.js?1693209103.176263:1227
    updateInput http://localhost:7860/file=javascript/ui.js?1692875047.160491:338
    insertTextAtCursor http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/tagAutocomplete.js?1693209103.176263:535
    navigateInList http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/tagAutocomplete.js?1693209103.176263:1158
    addAutocompleteToArea http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/tagAutocomplete.js?1693209103.176263:1237
[ext_wildcards.js:38:44](http://localhost:7860/file=I:/Super%20SD%202.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/ext_wildcards.js?1693209103.176263)
17:06:17.561
Error loading file "extensions/sd-dynamic-prompts/wildcards//clothing_light_women.txt?1693238777547": 403 Forbidden [_utils.js:48:17](http://localhost:7860/file=I:/Super%20SD%202.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/_utils.js?1693209103.1752656)
17:06:17.561
Uncaught (in promise) TypeError: null has no properties
    parse http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/ext_wildcards.js?1693209103.176263:38
    processQueueReturn http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/_utils.js?1693209103.1752656:214
    processParsers http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/_utils.js?1693209103.1752656:231
    autocomplete http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/tagAutocomplete.js?1693209103.176263:991
    keepOpenIfWildcard http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/ext_wildcards.js?1693209103.176263:158
    processQueueReturn http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/_utils.js?1693209103.1752656:214
    insertTextAtCursor http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/tagAutocomplete.js?1693209103.176263:548
    navigateInList http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/tagAutocomplete.js?1693209103.176263:1158
    addAutocompleteToArea http://localhost:7860/file=I:/Super SD 2.0/automatic/extensions/a1111-sd-webui-tagcomplete/javascript/tagAutocomplete.js?1693209103.176263:1237

Is it that what you mentioned with "adding the path"? But why doesn't it work when it did 'always'? And what exactly do I have to do to solve this? 🤔

**Comment by DominikDoom** [comment]
If you didn't change the paths this shouldn't make a difference. It might be related to this update https://github.com/vladmandic/automatic/commit/53dcf157fb8daa054917ffef04102c047192a5ac but since it works for me on a later version, I'm not sure what the issue is in your case.

if you just paste and run the following line in your browser console on the webui page, does it return anything or error out?
```js
await (await fetch("file=extensions/sd-dynamic-prompts/wildcards/clothing_light_women.txt?1234567890")).text()
```

**Comment by DominikDoom** [comment]
Another idea to try out would be if it works in another browser or incognito mode, since it could be a browser extension that blocks the request.

**Comment by Woisek** [comment]
> if you just paste and run the following line in your browser console on the webui page, does it return anything or error out?

This:
`{"error":"HTTPException","detail":"File not allowed: extensions/sd-dynamic-prompts/wildcards/clothing_light_women.txt.","body":"","errors":"(403, 'File not allowed: extensions/sd-dynamic-prompts/wildcards/clothing_light_women.txt.')"}`

> By the way, when I was talking about the browser console,

NP, I'm aware of what you mean, I'm a developer myself. 🙂

>Another idea to try out would be to check if it works in another browser or incognito mode, since it could be a browser extension that blocks the request.

I run SD in a own profile of FF with only 3 extensions that are ad related and image converting related.

But your console command looks like the f*cking Gradio is again making problems. Or do you have another suggestion? 🤔
Thanks by the way for the fast help. 👍

**Comment by DominikDoom** [comment]
If the file isn't outside of the root I don't think it's gradio, although tbh you can never be sure with them.
But it works on a fresh sd next install for me, with a folder structure very similar to yours, so in theory it should be comparable.
Maybe recreate the venv to ensure the versions are correct?

I would still advise you to try in a Chromium based browser just to make sure, since I haven't tried to replicate it in Firefox so far.

**Comment by Woisek** [comment]
What is still the case and has always worked is that the folder to the wildcard is a windows junction.
Since I run multiple versions of different UIs and don't want to have everything duplicated and triplicated, different folders are linked by junction. And so far this has never been a problem.
Normal, a junction should not be notices as such in any case because ... it's a junction. 😄 But maybe that's the issue to be solved ... ?! 🤔

**Comment by DominikDoom** [comment]
Could very well be the case, maybe the change to relative paths in the commit I linked messed something up with junction handling. You could try adding the real junction root folder to the allowed paths argument I mentioned at the beginning.

**Comment by Woisek** [comment]
> You could try adding the real junction root folder to the allowed paths argument I mentioned at the beginning.

Is this added in the SD:Next startup bat file? How should it look like? 🤔

**Comment by DominikDoom** [comment]
If the SD.Next startup bat has a command line args variable it can probably go there, but a separate bat that just calls the startup one with the argument appended would be better. Or directly from the terminal if you just want to test it temporarily.

`--gradio-allowed-path "<path here>"` should work if the argument is the same.

But as I said, if you can't get it to work that way I'll probably be able to properly fix it / work around it soon-ish.

**Comment by Woisek** [comment]
> If the SD.Next startup bat has a command line args variable it can probably go there,

It has args, but I don't know if --gradio-allowed-path is supported.

> Or directly from the terminal if you just want to test it temporarily.

Okay, now I'm not sure what you mean with 'terminal'. 😄 Some hint, please?

**Comment by DominikDoom** [comment]
Well, just cmd or Powershell or whatever your favorite shell is.

**Comment by Woisek** [comment]
Hmm ... still not sure, but I will look into it.
Thanks meanwhile. 👍

**Comment by DominikDoom** [comment]
I reworked it to use its own API endpoint, so I think it should work for you now. Feel free to reopen if you still have the issue after updating.

**Comment by Woisek** [comment]
Many thanks, will look into it later on. 👍
